name             'koop_osm_provider'
maintainer       'Chris Helm'
maintainer_email 'chritopher_helm@esri.com'
license          'All rights reserved'
description      'Contains system requirements for Koop OSM'
long_description 'Contains system requirements for Koop OSM'
version          '0.1.0'
